name: dyslexia_app
description: This project is a mobile application provides some exercises for children who suffer from Dyslexia. In this project, we connected with a Dyslexia Specialist called Dr. Gad Elbeheri and we used some the exercises he recommended it to us. The application frontend built entirely using Flutter Framework and the backend built using Firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  email_validator: '^1.0.5'
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.12.0
  flip_card: ^0.4.4
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  provider: ^5.0.0
  flutter_spinkit: "^4.1.2"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 600

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
